### ISSUE TITLE
Role defined for FlowLogActivator cannot be assumed by Lambda

### ISSUE THREAD

**Issue by camados** [aws-samples/aws-ct-vpc-flowlogs#1]
Error message:
`ResourceLogicalId:FlowLogActivator, ResourceType:AWS::Lambda::Function, ResourceStatusReason:Resource handler returned message: "The role defined for the function cannot be assumed by Lambda. (Service: Lambda, Status Code: 400, Request ID: b3ca3772-7cf9-484d-aed6-34c758a5325e, Extended Request ID: null)"`

It looks like the role for the FlowLogActivator lambda function cannot be assumed by lambda, although this looks correct in the CF Template.

Steps to reproduce:
Follow steps in https://aws.amazon.com/blogs/mt/using-aws-cost-usage-reports-cost-allocation-tags-to-understand-vpc-flow-logs-data-ingestion-costs-in-amazon-s3/
I used the Log Archive account in our org as the hub account.

**Comment by wellsiau-aws** [comment]
closing this
tracking potential improvement [here](https://github.com/aws-samples/aws-ct-vpc-flowlogs/issues/2)
