### ISSUE TITLE
SSM Parameter /org/core/ManagementAccountId is not defined

### ISSUE THREAD

**Issue by vhartikainen** [aws-samples/aws-ct-vpc-flowlogs#16]
When applying the customization, the CfCT pipeline will fail in "CloudformationResource" stage.

Error message seen in the logs is quite clear. Seems like this SSM parameter is not created.
`
{"time_stamp": "2022-06-21 19:32:47,249","log_level": "ERROR","log_message": Unhandled Exception: The SSM Parameter /org/core/ManagementAccountId was not found}
`

**Comment by wellsiau-aws** [comment]
solved on #18 , thank you!
