### ISSUE TITLE
Python 3.7 No longer supported

### ISSUE THREAD

**Issue by kaiz-io** [aws-samples/aws-ct-vpc-flowlogs#26]
Solution currently using a no longer supported version of Python runtime. Needs to be updated to a supported version. Probaly needs to be combine with  #25 .

[./cfct/templates/vpc_flowlog_automation_in_hub.template#L227](https://github.com/aws-samples/aws-ct-vpc-flowlogs/blob/main/cfct/templates/vpc_flowlog_automation_in_hub.template?plain=1#L227)

**Comment by mmarthab** [comment]
Hi, I am also getting the same error on my end. ... "Resource handler returned message: "The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.12) while creating or updating functions.  This is on deploying/setting up the lifecycle event part.

**Comment by wellsiau-aws** [comment]
thanks for raising this issue and I apologize for long delay. I am taking a look at this issue now.
