### ISSUE TITLE
"Cancelled since failure tolerance has exceeded" &  "The role defined for the function cannot be assumed by Lambda."

### ISSUE THREAD

**Issue by clin0** [aws-samples/aws-ct-vpc-flowlogs#4]
Hi, I followed your post and showed the following error in my Master account under StackSet details.  
Both my master account and Hub account (a.k.a Log Achieve account) use US-EAST-2 Ohio as the default region.
The member account used US-EAST-1. Deployed StackSets into regions sequentially.
Thank you for your help.

Show as below
![ct-flowlog-error](https://user-images.githubusercontent.com/44655719/140810879-e3f01042-7a61-42cb-895c-cc6125bfbd66.jpg)

**Comment by wellsiau-aws** [comment]
thanks for reporting this issue, its seems to me that there are race condition when the role is not ready yet to be referenced by Lambda.

this might occur if you are deploying the stackset in multiple region with parallel concurrency as described [here](https://github.com/aws-samples/aws-ct-vpc-flowlogs/issues/1)

can you try to redeploy it with one of the following options:
1. Do not use parallel concurrency 
2. Deploy to home region first and then add stackset instance for the rest of the region with parallel concurrency turned on again.

**Comment by clin0** [comment]
Hey, thank you for your quick response. Solved the problem by Option 2. Thank a lot

**Comment by wellsiau-aws** [comment]
Thanks, I will close this issue now
