### ISSUE TITLE
Issue : CfCT - duplicate flowlogs on Subnet and VPC during first run

### ISSUE THREAD

**Issue by wellsiau-aws** [aws-samples/aws-ct-vpc-flowlogs#8]
For CfCT mode, we trigger first-run to inspect all VPCs and Subnets.

If the `DefaultTrafficLoggingMode` is set to enable flow logs (all, reject, accept), then there will be duplicate on both VPC and Subnet level.

Proposed fix: 

`DefaultTrafficLoggingMode` should only apply to VPC resource. During tag parsing, check the resource type and set default value accordingly.

**Comment by wellsiau-aws** [comment]
Ref to PR for CfCT (https://github.com/aws-samples/aws-ct-vpc-flowlogs/pull/5)

**Comment by str3tch** [comment]
this is fixed with the merged PR now is it not @wellsiau-aws ?

**Comment by wellsiau-aws** [comment]
@str3tch , yes you are correct, I will close this issue now. Thanks!
